services:
  api:
    image: r3igar/language_learner_x86:x86
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_DB=${NEO4J_DB}

      - NEO4J_dbms_memory_pagecache_size=128M   # Lower pagecache size
      - NEO4J_dbms_memory_heap_initial_size=128M # Lower initial heap size
      - NEO4J_dbms_memory_heap_max_size=256M    # Lower maximum heap size
      
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: neo4j:latest
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - db:/var/lib/neo4j/data

volumes:
  db:
    driver: local
