services:
  api:
    image: r3igar/language_learner_arm:arm
    environment:
      - NEO4J_dbms_memory_pagecache_size=1G  # Adjust the size of the pagecache (e.g., 1GB)
      - NEO4J_dbms_memory_heap_initial_size=512m  # Set the initial heap size (e.g., 512MB)
      - NEO4J_dbms_memory_heap_max_size=2G  # Set the maximum heap size (e.g., 2GB)

      - NEO4J_URI=172.17.0.1:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=LimU74JJ6hFfjzBrhRpIm3y9aD_tJ1PqOBXIfRjxw-g
      - NEO4J_DB=neo4j
      
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: neo4j:latest
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - db:/var/lib/neo4j/data

volumes:
  db:
    driver: local
